apiVersion: app.philipkrueck.com/v1alpha1
kind: Philip
metadata:
  labels:
    app.kubernetes.io/name: basic-operator
    app.kubernetes.io/managed-by: kustomize
  name: philip-sample
spec:
  # TODO(user): Add fields here
